<?php
/**
 * @file panels_node.module
 *
 * This module provides the "panel" node type.
 * Panel nodes are useful to add additional content to the content area
 * on a per-node base.
 */

// ---------------------------------------------------------------------------
// General Backdrop hooks.

/**
 * layout_preprocess_layout() adds all these page components to templates 
 * whether you want them or not, meaning they show up twice: once when the page 
 * is rendered and again when this node layout is rendered, except if 'admin' 
 * is true.
 */
function panels_node_preprocess_layout(&$variables) {
  $variables += array(
    'action_links' => '',
    'tabs' => '',
    'title' => '',
  );
  if ($variables['layout']->settings['panels_node']) {
    $variables['admin'] = TRUE;
  }
}

/**
 * Implements hook_permission().
 */
function panels_node_permission() {
  return array(
    'administer panel-nodes' => array(
      'title' => t('Administer panel nodes'),
      'description' => t('Full administrative access to panel nodes including create, update and delete all'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function panels_node_menu() {
  $items['admin/structure/panels/settings/panel-node'] = array(
    'title' => 'Panel nodes',
    'description' => 'Configure which content is available to add to panel node displays.',
    'access arguments' => array('administer panel-nodes'),
    'page callback' => 'panels_node_settings',
    'type' => MENU_LOCAL_TASK,
  );

  // Avoid some repetition on these:
  $base = array(
    'access callback' => 'panels_node_edit_node',
    'access arguments' => array(1),
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );

  $items['node/%node/panel_layout'] = array(
    'title' => 'Panel layout',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('panels_node_edit_layout', 1),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'panels_node_edit_node',
    'access arguments' => array(1),
  );

  $items['node/%node/panel_content'] = array(
    'title' => 'Panel content',
    'page callback' => 'panels_node_edit_content',
    'weight' => 3,
  ) + $base;

  $items['node/add/panel/choose-layout'] = array(
    'title' => 'Choose layout',
    'access callback' => 'panels_add_panel_access_callback',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('panels_node_add'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Access callback to determine if a user has edit access.
 */
function panels_node_edit_node($node) {
  if (!isset($node->panels_node)) {
    return FALSE;
  }

  return node_access('update', $node);
}

/**
 * Access callback to determine if user has access to add panel nodes.
 */
function panels_add_panel_access_callback() {
  return user_access('create panel content') || user_access('administer panel-nodes');
}

function panels_node_admin_paths_alter(&$paths) {
  $paths['node/*/panel_layout'] = TRUE;
  $paths['node/*/panel_content'] = TRUE;
}

/**
 * Override of node add page to force layout selection prior
 * to actually editing a node.
 */
function panels_node_add($form, &$form_state) {
  backdrop_set_title(t('Create Panel node'));
  $form['#attached']['js'][] = backdrop_get_path('module', 'layout') . '/js/layout.admin.js';
  $form['#attached']['css'][] = backdrop_get_path('module', 'layout') . '/css/layout.admin.css';
  $form['#attributes'] = array('class' => array('layout-settings-form'));

  $form['layout_template'] = array(
    '#title' => t('Layout template'),
    '#type' => 'radios',
    '#default_value' => $layout->layout_template,
    '#options' => array(),
    '#wrapper_attributes' => array('class' => array('clearfix', 'layout-options')),
    '#required' => TRUE,
  );

  // Get the list of layout template options.
  $all_template_info = layout_get_layout_template_info();
  $excluded = config_get('layout.settings', 'excluded_templates');
  foreach ($all_template_info as $template_name => $template_info) {
    if (!in_array($template_name, $excluded)) {
      $form['layout_template']['#options'][$template_name] = theme('layout_template_option', array('template_info' => $template_info));
    }
  }
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create panel node'),
  );

  return $form;
}

function panels_node_add_submit($form, &$form_state) {
  backdrop_goto('node/add/panel/' . $form_state['values']['layout_template']);
}

// ---------------------------------------------------------------------------
// Node hooks.
/**
 * Implements hook_access().
 */
function panels_node_node_access($node, $op, $account) {
  if ($op == 'create' && $node != 'panel') {
    return NODE_ACCESS_IGNORE;
  }

  if (is_object($node) && $node->type != 'panel') {
    return NODE_ACCESS_IGNORE;
  }

  if (user_access('administer panel-nodes', $account)) {
    return NODE_ACCESS_ALLOW;
  }
}

/**
 * Implements hook_form().
 */
function panels_node_hook_form(&$node, &$form_state) {
  $form['panels_node']['#tree'] = TRUE;
  if (empty($node->nid) && arg(0) == 'node' && arg(1) == 'add') {
    // Grab our selected layout from the $node, If it doesn't exist, try arg(3)
    // and if that doesn't work present them with a list to pick from.
    $layout_template = isset($node->panel_layout) ? $node->panel_layout : arg(3);
    if (empty($layout_template)) {
      backdrop_goto('node/add/panel/choose-layout', array('query' => backdrop_get_query_parameters()));
    }

    $layout_template_info = layout_get_layout_template_info($layout_template);
    if (empty($layout_template_info)) {
      return MENU_NOT_FOUND;
    }
    $form['panels_node']['layout'] = array(
      '#type' => 'value',
      '#value' => $layout_template,
    );
  }

  $type = node_type_get_type($node);

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
  );

  $css_id = '';
  if (!empty($node->panels_node['css_id'])) {
    $css_id = $node->panels_node['css_id'];
  }

  $form['panels_node']['css_id'] = array(
    '#type' => 'textfield',
    '#title' => t('CSS ID'),
    '#size' => 30,
    '#description' => t('An ID that can be used by CSS to style the panel.'),
    '#default_value' => $css_id,
  );

  $form['panels_node']['pipeline'] = array(
    '#type' => 'value',
    '#value' => 'standard',
  );

  return $form;
}

/**
 * Implements hook_validate().
 */
function panels_node_hook_validate($node, $form, &$form_state) {
  if (!$node->nid && empty($node->panels_node['layout'])) {
    form_error($form['panels_node']['layout'], t('Please select a layout.'));
  }
}

/**
 * Implements hook_load().
 *
 * Panels does not use revisions for nodes because that would open us up
 * to have completely separate displays, and we'd have to copy them,
 * and that's going to be a LOT of data.
 */
function panels_node_hook_load($nodes) {
  // We shortcut this because only in some really drastic corruption circumstance will this
  // not work.
  $result = db_query("SELECT * FROM {panels_node} WHERE nid IN (:nids)", array(':nids' => array_keys($nodes)));
  foreach ($result as $record) {
    $nodes[$record->nid]->panels_node = (array) $record;
  }
}

/**
 * Implements hook_insert().
 */
function panels_node_hook_insert(&$node) {
  $config = array(
    'is_new' => TRUE,
  );
  // Create a new display and record that.
  $display = new Layout($config);
  $display->layout_template = $node->panels_node['layout'];
  $display->name = 'test_name'; // will need to build unique name from title or NID.
  // $display->storage_type = 'panels_node';
  // $display->storage_id = $node->nid;

/*   // Special handling for nodes being imported from an export.module data dump.
  if (!empty($node->export_display)) {
    // This works by overriding the $display set above.
    eval($node->export_display);
    unset($node->export_display);
  }
 */
  $display->save();
  $node->panels_node['did'] = $display->name;

  db_insert('panels_node')
    ->fields(array(
    'nid' => $node->nid,
    'did' => $display->name,
    'css_id' => $node->panels_node['css_id'],
    'pipeline' => $node->panels_node['pipeline'],
  ))
    ->execute();
}

/**
 * Implements hook_delete().
 */
function panels_node_hook_delete(&$node) {
  db_delete('panels_node')->condition('nid', $node->nid)->execute();
  if (!empty($node->panels_node['did'])) {
    panels_delete_display($node->panels_node['did']);
  }
}

/**
 * Implements hook_update().
 */
function panels_node_hook_update($node) {
  db_update('panels_node')
    ->condition('nid', $node->nid)
    ->fields(array(
    'css_id' => $node->panels_node['css_id'],
    'pipeline' => $node->panels_node['pipeline'],
  ))
    ->execute();
}

/**
 * Implements hook_view().
 */
function panels_node_hook_view($node, $view_mode) {
  static $rendering = array();

  // Prevent loops if someone foolishly puts the node inside itself:
  if (!empty($rendering[$node->nid])) {
    return $node;
  }

  $rendering[$node->nid] = TRUE;

  if ($view_mode == 'teaser') {
    // Because our teasier is never the same as our content, *always* provide
    // the read more flag.
    $node->readmore = TRUE;
  }
  else {
    if (!empty($node->panels_node['did'])) {
      $display = layout_load($node->panels_node['did']);
      // This lets us know if a template is being used by the page or the node.
      $display->settings['panels_node'] = TRUE;
      $display->css_id = $node->panels_node['css_id'];
      // TODO: Find a way to make sure this can't node_view.
      // $display->context = panels_node_get_context($node);
      $display->cache_key = 'panels_node:' . $node->nid;
      $renderer = layout_create_renderer('standard', $display);
      $node->content['body'] = array(
        '#markup' => $renderer->render(),
        '#weight' => 0,
      );
    }
  }

  unset($rendering[$node->nid]);
  return $node;
}

// ---------------------------------------------------------------------------
// Administrative pages.
/**
 * Settings for panel nodes.
 */
function panels_node_settings() {
  return backdrop_get_form('panels_common_settings', 'panels_node');
}

// ---------------------------------------------------------------------------
// Meat of the Panels API; almost completely passing through to panels.module.
/**
 * Pass through to the panels layout editor.
 */
function panels_node_edit_layout($form, &$form_state, $node) {
  $form['#attached']['js'][] = backdrop_get_path('module', 'layout') . '/js/layout.admin.js';
  $form['#attached']['css'][] = backdrop_get_path('module', 'layout') . '/css/layout.admin.css';

  $layout = layout_load($node->panels_node['did']);
  form_load_include($form_state, 'inc', 'layout', 'layout.admin');

  $form_state['layout'] = &$layout;

  $form['#attributes'] = array('class' => array('layout-settings-form'));

  $form['layout_template'] = array(
    '#title' => t('Layout template'),
    '#type' => 'radios',
    '#default_value' => $layout->layout_template,
    '#options' => array(),
    '#wrapper_attributes' => array('class' => array('clearfix', 'layout-options')),
    '#required' => TRUE,
  );

  // Get the list of layout template options.
  $all_template_info = layout_get_layout_template_info();
  $excluded = config_get('layout.settings', 'excluded_templates');
  foreach ($all_template_info as $template_name => $template_info) {
    if (!in_array($template_name, $excluded)) {
      $form['layout_template']['#options'][$template_name] = theme('layout_template_option', array('template_info' => $template_info));
    }
  }
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save layout template'),
    // '#validate' => array(
      // 'layout_settings_form_validate',
    // ),
    '#submit' => array(
      'layout_settings_form_update_layout',
      'panels_node_edit_layout_submit',
    ),
  );

  return $form;
}

/**
 * Pass through to the panels content editor.
 */
function panels_node_edit_layout_submit($form, &$form_state) {
  $layout = $form_state['layout'];
  $layout->save();

  layout_clear_layout_tempstore($layout->name);
  if (!empty($layout->is_new)) {
    backdrop_set_message(t('Layout created. Blocks may now be added to this layout.'));
  }
  else {
    backdrop_set_message(t('Layout saved.'));
  }
}

/**
 * Pass through to the panels content editor.
 */
function panels_node_edit_content($node) {
//  ctools_include('plugins', 'panels');
  // ctools_include('context');
  $display = layout_tempstore_load($node->panels_node['did']);

  // $display->context = panels_node_get_context($node);
  module_load_include('inc', 'layout', 'layout.admin');
  return backdrop_get_form('layout_content_form', $display);
}


